### ISSUE TITLE
Pecha Tools:  word segmentation staging / Data Preperation

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/pecha-tool-for-word-segmentation#6]
### Description

Since sentence segmentation work is about to be finished and get reviewed by data analyst, we need to have word segmentation ready for Dictionary data.

### Completion Criteria

- All description data of Monlam dictionary need to get parsed and  word segmented 

### Implementation Plan

i need to make a pipeline to parse tibetan text from eng to tibetan  (monlam dictionary data), and import it in word segmentation database, since the data base file is large , i think we can query the description alphabetically and parse the description one by one,

### Subtasks

- [x] parse monlam dictionary Eng-Tib data (SQLITE)
- [x] fetch the data alphabetically on the key, and parse description for word segmentation usecases.
- [x] perform wordsegmentation  using botok
- [x] import the data in the word segmentation database
- [x] test if the word segmentation render the data properly.
