### ISSUE TITLE
Limit user work per week

### ISSUE THREAD

**Issue by tenkus47** [OpenPecha/pecha-tool-for-word-segmentation#7]
### Description

we need to implement a limit for each user for words per week, due to budget issue.  

### Completion Criteria

- each user will get a specific number of word per week and if the number reach that limit the task will not be assigned to them

### Implementation Plan

- we need to keep track of how much task is completed by the user with word count
- provide new task only if the word count limit is not reached

### Subtasks

- [x] store word count per task in database
- [x] calculate total count before assigning the new task
- [x] show limit message if limit is reached
- [x] assign full text to each user
- [x] each text should contain similar number of word

**Comment by tenkus47** [comment]
each user should be assigned with a similar number of task

should consider number of word per month too
